// Mock data for OpenClaw Managed Agents dashboard

const AGENTS = [
  {
    id: 'ag_7k2fLq',
    name: 'research-assistant',
    model: 'moonshot/kimi-k2.5',
    version: 4,
    tools: ['web.search', 'web.fetch', 'file.write', 'python'],
    mcp: ['linear', 'notion'],
    policy: 'always_ask',
    sessions: 142,
    cost24h: '$4.82',
    updated: '2h ago',
  },
  {
    id: 'ag_h9b1vM',
    name: 'telegram-bridge',
    model: 'anthropic/claude-haiku-4.5',
    version: 12,
    tools: ['channels.send', 'channels.subscribe'],
    mcp: [],
    policy: 'always_allow',
    sessions: 2104,
    cost24h: '$11.40',
    updated: '9m ago',
  },
  {
    id: 'ag_3xP0aE',
    name: 'inbox-triage',
    model: 'openai/gpt-5-mini',
    version: 2,
    tools: ['gmail.read', 'gmail.label', 'web.fetch'],
    mcp: ['gmail'],
    policy: 'deny',
    sessions: 88,
    cost24h: '$0.94',
    updated: '1d ago',
  },
  {
    id: 'ag_Wq8oYt',
    name: 'lease-watch',
    model: 'google/gemini-2.5-flash',
    version: 1,
    tools: ['signal.read', 'notify'],
    mcp: [],
    policy: 'always_allow',
    sessions: 6,
    cost24h: '$0.01',
    updated: '3d ago',
  },
];

const SESSIONS = [
  {
    id: 'sx_a91c8b42',
    agent: 'research-assistant',
    agentId: 'ag_7k2fLq',
    model: 'moonshot/kimi-k2.5',
    status: 'running',
    started: '2m ago',
    wallMs: 142_300,
    tokens: 8_412,
    tokensCap: 50_000,
    cost: 0.063,
    costCap: 1.00,
    turns: 4,
    env: 'env_py_stdlib',
    container: 'oc-sx-a91c8b42',
    pool: 'warm-reuse',
    bootMs: 4_100,
  },
  {
    id: 'sx_7712dd09',
    agent: 'telegram-bridge',
    agentId: 'ag_h9b1vM',
    model: 'anthropic/claude-haiku-4.5',
    status: 'running',
    started: '14m ago',
    wallMs: 842_000,
    tokens: 24_140,
    tokensCap: 50_000,
    cost: 0.181,
    costCap: 2.00,
    turns: 22,
    env: 'env_default',
    container: 'oc-sx-7712dd09',
    pool: 'warm-reuse',
    bootMs: 3_900,
  },
  {
    id: 'sx_4203ff21',
    agent: 'research-assistant',
    agentId: 'ag_7k2fLq',
    model: 'moonshot/kimi-k2.5',
    status: 'awaiting',
    started: '1m ago',
    wallMs: 38_000,
    tokens: 1_204,
    tokensCap: 50_000,
    cost: 0.014,
    costCap: 1.00,
    turns: 1,
    env: 'env_py_stdlib',
    container: 'oc-sx-4203ff21',
    pool: 'cold',
    bootMs: 78_200,
  },
  {
    id: 'sx_8a0e2c17',
    agent: 'lease-watch',
    agentId: 'ag_Wq8oYt',
    model: 'google/gemini-2.5-flash',
    status: 'idle',
    started: '3h ago',
    wallMs: 11_042_100,
    tokens: 812,
    tokensCap: 50_000,
    cost: 0.004,
    costCap: 1.00,
    turns: 2,
    env: 'env_default',
    container: 'oc-sx-8a0e2c17',
    pool: 'warm-reuse',
    bootMs: 4_000,
  },
  {
    id: 'sx_ff21aa10',
    agent: 'inbox-triage',
    agentId: 'ag_3xP0aE',
    model: 'openai/gpt-5-mini',
    status: 'failed',
    started: '1d ago',
    wallMs: 1_200,
    tokens: 112,
    tokensCap: 50_000,
    cost: 0.001,
    costCap: 1.00,
    turns: 1,
    env: 'env_default',
    container: '—',
    pool: 'cold',
    bootMs: 82_100,
    error: 'gmail.read denied by permission policy',
  },
  {
    id: 'sx_1c88bb0a',
    agent: 'telegram-bridge',
    agentId: 'ag_h9b1vM',
    model: 'anthropic/claude-haiku-4.5',
    status: 'ended',
    started: '2d ago',
    wallMs: 4_182_000,
    tokens: 42_101,
    tokensCap: 50_000,
    cost: 0.312,
    costCap: 2.00,
    turns: 34,
    env: 'env_default',
    container: '—',
    pool: 'warm-reuse',
    bootMs: 4_200,
  },
  {
    id: 'sx_b54c9100',
    agent: 'research-assistant',
    agentId: 'ag_7k2fLq',
    model: 'moonshot/kimi-k2.5',
    status: 'quota',
    started: '5h ago',
    wallMs: 9_100_000,
    tokens: 49_812,
    tokensCap: 50_000,
    cost: 0.982,
    costCap: 1.00,
    turns: 18,
    env: 'env_py_stdlib',
    container: 'oc-sx-b54c9100',
    pool: 'warm-reuse',
    bootMs: 4_100,
    error: 'maxCostUsdPerSession hit: $0.982 / $1.000',
  },
];

// Live event stream for the focused session sx_a91c8b42
const EVENTS = [
  { t: '+00:00.142', type: 'session.status_running',  actor: 'orchestrator' },
  { t: '+00:00.418', type: 'user.message',            actor: 'user',
    text: 'Summarize the managed-agent platform landscape in 2026. Pull real citations. Save as research.md.' },
  { t: '+00:01.027', type: 'agent.thinking',          actor: 'kimi-k2.5',
    text: "Okay — I'll break this into three buckets: hyperscaler-native (Claude Managed Agents, OpenAI Responses API, Gemini Vertex Agents), open-source runtimes (OpenClaw, LangGraph Cloud, CrewAI Enterprise), and BYOC wrappers. I'll need web.search for primary sources and file.write to save the output." },
  { t: '+00:01.601', type: 'agent.tool_use',          actor: 'kimi-k2.5',
    tool: 'web.search', args: { q: 'claude managed agents pricing 2026', max: 8 }, toolUseId: 'tu_01' },
  { t: '+00:02.840', type: 'agent.tool_result',       actor: 'web.search',
    toolUseId: 'tu_01', summary: '8 results · 1.2s · cached', isError: false },
  { t: '+00:02.991', type: 'agent.tool_use',          actor: 'kimi-k2.5',
    tool: 'web.fetch', args: { url: 'anthropic.com/news/managed-agents-2026-pricing' }, toolUseId: 'tu_02' },
  { t: '+00:04.210', type: 'agent.tool_result',       actor: 'web.fetch',
    toolUseId: 'tu_02', summary: '42 KB · text/html · 0.9s', isError: false },
  { t: '+00:04.380', type: 'agent.tool_use',          actor: 'kimi-k2.5',
    tool: 'file.write', args: { path: 'research.md', bytes: 4810 }, toolUseId: 'tu_03',
    needsApproval: true },
  { t: '+00:04.412', type: 'agent.tool_confirmation_request', actor: 'orchestrator',
    toolUseId: 'tu_03', policy: 'always_ask',
    prompt: 'Agent wants to write research.md (4.8 KB) to the session container' },
];

// Partial streaming tokens for the next agent.message (shown cursor-blinking)
const STREAMING_TOKENS = "Two distinct layers have emerged in 2026. The **hyperscaler-native** tier (Anthropic Managed Agents, OpenAI Responses, Gemini Vertex) is closed-source but solid engineering — real token streaming, versioning, audit. The **open tier**";

const AUDIT_ROWS = [
  { ts: '2026-04-19 14:02:11.481Z', actor: 'token.af1e…', action: 'session.create',     target: 'sx_a91c8b42', outcome: 'ok' },
  { ts: '2026-04-19 14:02:10.204Z', actor: 'token.af1e…', action: 'agent.patch',        target: 'ag_7k2fLq',   outcome: 'ok' },
  { ts: '2026-04-19 13:57:02.118Z', actor: '10.0.0.42',    action: 'session.create',     target: 'sx_4203ff21', outcome: 'ok' },
  { ts: '2026-04-19 13:51:40.002Z', actor: 'token.af1e…', action: 'agent.create',       target: 'ag_7k2fLq',   outcome: 'ok' },
  { ts: '2026-04-19 12:20:11.914Z', actor: 'token.91cb…', action: 'session.cancel',     target: 'sx_1c88bb0a', outcome: 'ok' },
  { ts: '2026-04-19 11:02:44.510Z', actor: 'token.91cb…', action: 'vault.credential.add', target: 'vl_notion01', outcome: 'ok' },
  { ts: '2026-04-19 09:44:01.112Z', actor: '10.0.0.42',    action: 'session.create',     target: 'sx_ff21aa10', outcome: 'rejected · deny:gmail.read' },
];

const STATS = [
  { label: 'Sessions · live',  value: '14',        sub: '3 awaiting' },
  { label: 'Warm pool',        value: '5 / 5',     sub: 'full' },
  { label: 'Tokens · 24h',     value: '4.21M',     sub: '+4.8%' },
  { label: 'Cost · 24h',       value: '$18.04',    sub: '−2.1%' },
  { label: 'Cold starts · 24h', value: '9',        sub: '78s avg' },
];

Object.assign(window, { AGENTS, SESSIONS, EVENTS, STREAMING_TOKENS, AUDIT_ROWS, STATS });
